variables:
- group: common
- template: /.azuredevops/variables-global.yml

parameters:
- name: aompRef
  type: string
  default: refs/tags/$(LATEST_RELEASE_TAG)
- name: extrasRef
  type: string
  default: refs/tags/$(LATEST_RELEASE_TAG)
- name: flangRef
  type: string
  default: refs/tags/$(LATEST_RELEASE_TAG)
- name: llvmRef
  type: string
  default: refs/tags/$(LATEST_RELEASE_TAG)

resources:
  repositories:
  - repository: aomp_repo
    type: github
    endpoint: ROCm
    name: ROCm/aomp
    ref: ${{ parameters.aompRef }}
  - repository: aomp-extras_repo
    type: github
    endpoint: ROCm
    name: ROCm/aomp-extras
    ref: ${{ parameters.extrasRef }}
  - repository: flang_repo
    type: github
    endpoint: ROCm
    name: ROCm/flang
    ref: ${{ parameters.flangRef }}
  - repository: llvm-project_repo
    type: github
    endpoint: ROCm
    name: ROCm/llvm-project
    ref: ${{ parameters.llvmRef }}

trigger: none
pr: none

jobs:
  - template: ${{ variables.CI_COMPONENT_PATH }}/aomp.yml
    parameters:
      checkoutRepo: aomp_repo
      checkoutRef: ${{ parameters.aompRef }}
